# Generated by Django 4.1.4 on 2022-12-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_product_slug_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
