# Generated by Django 4.1.4 on 2023-02-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
