# Generated by Django 4.1.4 on 2023-02-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0010_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
