# Generated by Django 4.1.4 on 2023-02-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
