# Generated by Django 4.1.4 on 2023-02-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0015_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
