# Generated by Django 4.1.4 on 2023-02-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_rename_user_order_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
