# Generated by Django 4.1.4 on 2023-02-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_rename_user_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, default='4', max_length=50),
        ),
    ]
