# Generated by Django 4.1.4 on 2023-04-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0022_customer_order_price_order_quantity_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Website.product'),
        ),
    ]
